// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SkinType } from "./SkinType";

export type ApiTexture = { id: string | null, skin_name: string, texture_type: SkinType, image_data: string, };
